ゲーム画面の描画
human-osaka-game-2018/Fujizono_Shooting pull request #21
Opened 2019-02-25 09:15 UTC by rikita-fujizono

ゲーム画面の描画処理の実装
Closes #7

2019-02-25 13:43 UTC, yahara-mitsuaki requested changes

2019-02-25 13:43 UTC, yahara-mitsuaki commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.cpp
> +	float WINDOW_HEIGHT = static_cast<float>(WINDOW->GetHeight());
WINDOW_HEIGHT となってますがこれは背景の高さじゃないのですか？
もし、そうなら幅と同じようにテクスチャクラスのメンバにした方がいいと思います

2019-02-25 13:43 UTC, yahara-mitsuaki commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.cpp
> +	float u = static_cast<float>(m_texture.GetSrcWidth()) / static_cast<float>(m_texture.GetWidth());
テクスチャのUVならメンバの方がよくないですか？

2019-02-25 13:43 UTC, yahara-mitsuaki commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_textureLeft_x = 128.f;
m_textureLeft_x ですが使われ方を見る限り左上といういみなのでm_textureTopLeft_x の方がよくないですか？
伴ってm_textureTopLeft_yも必要だと思います

2019-02-26 02:08 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_textureLeft_x = 128.f;
指摘1のコミットで直しました。

2019-02-26 03:02 UTC, taishi-matsumura reviewed
質問でーす。回答お願いします。

2019-02-26 03:02 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/GameScene.h
> +#include "../../GameLib/SceneManager/SceneBase/SceneBase.h"
ヘッダファイルの中で別のファイルを相対pathで指定するのは良くないと思います。

ヘッダファイルそのものはコンパイル対象では無くて、そのヘッダファイルをincludeしたcppファイルが(ヘッダファイルの内容が展開された状態で)コンパイルされるんですよね？
ということは、そのcppファイルがどこに配置されているかによって相対pathによる場所が変わってきませんか？

2019-02-26 03:02 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.cpp
> +	float u = static_cast<float>(m_texture.GetSrcWidth()) / static_cast<float>(m_texture.GetWidth());
このプルリクでの対応箇所では無いですが、 `GetSrcWidth()` `GetWidth()` というメソッド名は誤解を与えそうです。
SrcというのはSourceのことだと思いますが、「誰から見て」「どういう意味で」`Source` なのでしょうか？

2019-02-27 05:41 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.cpp
> +	float u = static_cast<float>(m_texture.GetSrcWidth()) / static_cast<float>(m_texture.GetWidth());
この場所でしか使わないからメンバにする必要がないと思ったのでここはこのままにしておきます。

2019-02-27 05:55 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/GameScene.h
> +#include "../../GameLib/SceneManager/SceneBase/SceneBase.h"
指摘2の修正のコミットで直しました。

2019-02-27 08:10 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/GameScene.h
> +#include "../../GameLib/SceneManager/SceneBase/SceneBase.h"
はい、こんな感じで他のファイルも同様に対応お願いします。

2019-02-27 08:19 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.cpp
> +	float WINDOW_HEIGHT = static_cast<float>(WINDOW->GetHeight());
幅はマジックナンバーなので定数にしていますが、高さはマジックナンバーではないので、メンバ変数を増やしたくないのでこのままでいきます。

2019-02-27 08:20 UTC, taishi-matsumura requested changes

2019-02-27 08:20 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_texture_width = 384.f;
他のメンバ変数はプレフィクス `m_` + LowerCamelとなっているので、### 
```suggestion
	const float m_textureWidth = 384.f;
```
では？

2019-02-27 08:27 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_texture_width = 384.f;
@yttmwork 
「インスタンスの生存中に値を保持しておく」という目的のメンバ変数と、これら定数の違いがわかりにくいので、個人的には定数は別の命名規則が欲しいところですが何が一般的ですかね？

自分は過去の案件では、定数は(C言語のdefineのように)
* 全て大文字
* 単語の区切りは `_`

でやっていましたが古臭い気もします。
Googleさんはプレフィックス `k` みたいですがあまり見掛けないかなぁ…
https://ttsuki.github.io/styleguide/cppguide.ja.html#Constant_Names

2019-02-27 08:35 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/GameScene.h
> +#include "../../GameLib/SceneManager/SceneBase/SceneBase.h"
他のファイルも直しました。

2019-02-27 09:08 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_texture_width = 384.f;
指摘3の修正のコミットで直しました。

2019-02-27 09:18 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_texture_width = 384.f;
関数内ローカルの定数にしたのですね。
良いと思います 👍

2019-02-27 09:19 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_texture_width = 384.f;
関数内の定数にすると同時に命名が変更されていることを確認しました。

2019-02-27 09:26 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/GameScene.h
> +#include "../../GameLib/SceneManager/SceneBase/SceneBase.h"
プロジェクトのルートディレクトリにpath通したのであればcppの中での相対path指定も不要になったように思いますが、一旦これで進めましょうか。

2019-02-27 09:26 UTC, taishi-matsumura approved these changes

2019-02-27 09:27 UTC, taishi-matsumura commented
八原からの承認が出たら、コミット整理してマージしてしまいましょう。
そこまでいけばレビュー通っているので自分でマージボタン押してしまっても良いと思います。

2019-02-27 09:40 UTC, yahara-mitsuaki approved these changes
問題ないと思います！

2019-02-27 09:54 UTC, merged

2019-02-27 10:14 UTC, yttmwork commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_texture_width = 384.f;
@taishi-matsumura 
お疲れ様です。
defineと同じように大文字と_で構成されてるものを多く見ました。
あとは、パスカルケースですかね。
一般的となるとちょっと今までの環境的に自信ないです。
kをプレフィックスにしているものはまったく見かけたことないですね。

2019-02-27 10:48 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	const float m_texture_width = 384.f;
@yttmwork 
ですよねー。
結局、関数内にPascalCaseで定数作ったようなのでオッケーにしておきました。