攻撃弾の実装
human-osaka-game-2018/Fujizono_Shooting pull request #23
Opened 2019-02-28 08:48 UTC by rikita-fujizono

Closes #11

2019-02-28 09:06 UTC, taishi-matsumura requested changes
命名への指摘についてはサクっと終わらせてしまいましょう。
あと、vectorや配列の中身全件に対して何かをするときは範囲ベースfor文やfor eachの使用を検討して下さい。

2019-02-28 09:06 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	const float m_missileSpeed = 10.0f;
こいつだけ名前おかしい

2019-02-28 09:06 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +		m_missile[m_missile.size() -1].Missile_y = missile_y;
`m_missile.size() - 1` を何か変数に入れましょうか。
ぶっちゃけそこまでしなくても良いと思うのですが、練習だと思って。

2019-02-28 09:06 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	for (int i = 0; i < m_missile.size(); i++)
`m_missile` の全てに対して何かするんですよね？
範囲ベースforやfor eachの使用を検討して下さい。

2019-02-28 09:06 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	if (flag)
なんのフラグか意味わかりません 💩

2019-02-28 09:06 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.h
> +	void Update(bool flag, float missile_x, float missile_y);
Doxygenコメント書くのなら、引数のコメントも書いてね。

2019-02-28 09:08 UTC, Harutaka-Tsujino requested changes

2019-02-28 09:08 UTC, Harutaka-Tsujino commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	const char* m_texturePath = "../Graphics/Missile.jpg";
m_はメンバ変数につけるものでクラスのローカルには基本的に付けないですよ

2019-02-28 09:08 UTC, Harutaka-Tsujino commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.h
> +	struct MissileInfo
MissileInfoはほかのところでも使えるので名前を変えてインナークラスから外したほうがいいと思います

2019-02-28 09:18 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.h
> +	struct MissileInfo
使うところが出てきてからで良いのでは？

2019-02-28 09:27 UTC, taishi-matsumura requested changes

2019-02-28 09:27 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.h
> +	std::vector<MissileInfo> m_missile;
ミサイルが複数入るので、複数形にしておきましょか。

2019-02-28 09:27 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +		m_missile[m_missile.size() -1].Missile_y = missile_y;
この辺りの処理を `Update()` にやらせるのではなく、ミサイルの生成処理を別関数に切り出してはいかが？
で、ミサイルの初期位置は `MissileInfo` 自身にやらせてはいかが？
そうすれば謎のフラグが不要になると思います。

2019-02-28 09:46 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	const char* m_texturePath = "../Graphics/Missile.jpg";
名前の変更のコミットで直しました。

2019-02-28 09:46 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	const float m_missileSpeed = 10.0f;
名前の変更のコミットで直しました。

2019-02-28 10:29 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +		m_missile[m_missile.size() -1].Missile_y = missile_y;
ミサイルの生成処理関数の追加のコミットで直しました。

2019-02-28 10:32 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	if (flag)
ミサイルの生成処理関数の追加のコミットで直しました。

2019-02-28 11:23 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	for (int i = 0; i < m_missile.size(); i++)
for文を範囲Basefor文に変更のコミットで直しました。

2019-02-28 11:23 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.h
> +	std::vector<MissileInfo> m_missile;
for文を範囲Basefor文に変更のコミットで直しました。

2019-02-28 11:24 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.h
> +	void Update(bool flag, float missile_x, float missile_y);
Update関数に引数がなくなったので解決しました。

2019-02-28 15:59 UTC, taishi-matsumura requested changes
もう一声！

2019-02-28 15:59 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	}*/
DeadCodeなので消してしまいましょう

2019-02-28 15:59 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
>  }
ファイル末尾に改行入れときましょう

2019-02-28 15:59 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	MissileInfo Missile(missile_x, missile_y);
ローカル変数なので
```suggestion
	MissileInfo missile(missile_x, missile_y);
```
でしょうね。

2019-02-28 15:59 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +bool Missile::Initialize()
誰も戻り値見てないですね。
失敗する可能性があるのなら、エラー処理を呼び出し元に書きましょう。
他のクラスの `Initialize()` も同様。

2019-02-28 15:59 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	MissileInfo::x = missile_x;
```suggestion
	x = missile_x;
```
ではダメなの？

@yttmwork 
というか、ここで `MissileInfo::x` ってどういう意味になるんですか…？

2019-02-28 15:59 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.h
> +		MissileInfo(float missile_x, float missile_y);
`MissileInfo` がc'torで受け取るxとyはミサイルのxとyであることは自明なので
```suggestion
		MissileInfo(float x, float y);
```
で良いと思いますよ。

2019-02-28 16:04 UTC, taishi-matsumura commented
このプルリクでの実装内容をdescriptionに列挙しておいて下さい。
今後、他のプルリクも同様にお願いします。

プルリク作成時には具体的に書けないかもしれないので、WIP外すまでに書けばよいと思います。

2019-02-28 17:46 UTC, yttmwork commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	MissileInfo::x = missile_x;
@taishi-matsumura  
お疲れ様です。  
サンプル作って見たところ複数インスタンスを生成しても
きちんと各インスタンス毎に値が保存されるので、
this->と同等な意味合いになるんですかね？

2019-02-28 17:56 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	MissileInfo::x = missile_x;
@yttmwork 
おぉ、検証ありがとうございます。

だとしたら

2019-02-28 17:59 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	MissileInfo::x = missile_x;
@yttmwork 
おぉ、検証ありがとうございます。

@rikita-fujizono 
だとしたら、 `this->x = x;` の方がわかりやすいですね。
`MissileInfo::x` と書かれると、僕みたいなオジさんは「staticなメンバにアクセスしてる」みたいな印象を持ってしまいます。

2019-03-01 01:51 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
>  }
ファイル末尾に改行とDeadCodeの削除のコミットで直しました

2019-03-01 01:51 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	}*/
ファイル末尾に改行とDeadCodeの削除のコミットで直しました。

2019-03-01 02:06 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	MissileInfo::x = missile_x;
変数などの名前の変更のコミットで直しました。

2019-03-01 02:06 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.h
> +		MissileInfo(float missile_x, float missile_y);
変数などの名前の変更のコミットで直しました。

2019-03-01 02:06 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +	MissileInfo Missile(missile_x, missile_y);
変数などの名前の変更のコミットで直しました。

2019-03-01 03:31 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Player/Object/Missile.cpp
> +bool Missile::Initialize()
Initialize関数の戻り値の型をboolからvoidに変更で直しました。

2019-03-01 03:46 UTC, taishi-matsumura requested changes
エラー処理、実は作るのけっこう大変です。
例えばテクスチャオブジェクトの生成に失敗したまま処理を実行したら、その先のどこかでNULLポインタアクセス等で死ぬはずです。
そうなると各種解放処理を通らずメモリリークしたりするので、そうならないように「エラーが起きたらその旨をユーザに通知しつつ、正規ルートでの終了処理を行なった上でプログラムをきちんと終了する」というのが本来やるべきことです。

製品版ではそういうことも考えないといけないんだということは頭に置いておいて下さいね。

2019-03-01 03:46 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.cpp
> +		MessageBox(NULL, TEXT("画像の読み込みエラー"), TEXT("メッセージボックス"), MB_OK);
第3引数って、キャプション文字列ですよね？
もうちょっと意味のあるものにしません？
他の箇所も同様。

デバッガ使って無理矢理ここに来るようにすればメッセージボックスを表示させられるはずなので、もう少し試行錯誤してみて下さい。

2019-03-01 03:46 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	* @return 初期化が上手くできていないとFALSE
戻り値なくなったので、コメントも修正必要です。
他も同様。

2019-03-01 04:57 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.h
> +	* @return 初期化が上手くできていないとFALSE
無駄なコメントの削除のコミットで直しました。

2019-03-01 10:18 UTC, rikita-fujizono commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.cpp
> +		MessageBox(NULL, TEXT("画像の読み込みエラー"), TEXT("メッセージボックス"), MB_OK);
キャプションの文字をエラーに変更のコミットで直しました。

2019-03-01 10:31 UTC, taishi-matsumura commented on Shooting/Shooting/Scene/GameScene/Object/GameBackground.cpp
> +		MessageBox(NULL, TEXT("画像の読み込みエラー"), TEXT("メッセージボックス"), MB_OK);
エラー時のメッセージボックス表示処理がこれくらい増えてきたのならユーティリティ関数みたいなの作って欲しいところですが、弾と関係無いのでまた別でやりましょか。

2019-03-03 10:33 UTC, taishi-matsumura commented
@rikita-fujizono 
> このプルリクでの実装内容をdescriptionに列挙しておいて下さい。
今後、他のプルリクも同様にお願いします。

これやらないと、いつまで経ってもマージされないよ？

2019-03-04 11:03 UTC, taishi-matsumura commented
@rikita-fujizono 
descriptionが更新されていることを確認しました。
コミットが整理されたらマージします。
(コミットの整理をしてる内にdescriptionの内容がもう少し増えそうな気がしますが…)

2019-03-05 02:59 UTC, taishi-matsumura commented
```
[issue #11 clean] 各種初期化関数をリファクタリング

- 戻り値をvoidに変更
- エラー発生時はメッセージボックスを表示させる
```
```
[issue #11 add] ミサイルクラスを新規作成
```
くらいにコミットを分けましょうか。

2019-03-06 08:53 UTC, taishi-matsumura approved these changes

2019-03-06 08:55 UTC, taishi-matsumura commented
@Harutaka-Tsujino 
問題無ければ承認〜マージしてあげて下さい。(藤園的には履歴を一本線にしたいそうなので、Rebase and  mergeでお願いします)

2019-03-07 05:17 UTC, Harutaka-Tsujino approved these changes

2019-03-07 05:17 UTC, merged